### PR TITLE
API Namespace and update for ss 4.0

### PR DESCRIPTION
**Pull request by tractorcow**
Required for https://github.com/silverstripe/silverstripe-behat-extension/pull/152

### CODE REVIEW

**Comment by dhensby** [comment]
The test suite isn't running :/

**Comment by sminnee** [comment]
I think this is just a subsequent alpha for 2.x; why do we need to bump to 3?

**Comment by tractorcow** [comment]
> I think this is just a subsequent alpha for 2.x; why do we need to bump to 3?

We could make this 2.0, but we'd immediately break existing behat tests running on `^2@alpha`. The idea behind bumping to 3.0 is to prevent that. I'm willing to go either way if you feel one is safer.

**Comment by sminnee** [comment]
It just seems a bit odd as the target of the 2.x release was SS4-compatibility.

Something for another's discussion, but semantically each alpha release is essentially it's own major release. As such, anything that makes use of an alpha release should probably be tied to the specific release, and not a >= style dependency.

If we'd applied this a couple of releases ago with config, we wouldn't have had the alpha5 breakage.

**Pull request merged**
